# Site settings
title: "Developer Portfolio"
description: "Selected projects in Python, Control Systems, and Web Apps"
url: "https://pablomarcel.github.io"
baseurl: "/dev"

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "contrast"

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: false
      toc: true
      toc_label: "On this page"
      toc_icon: "list"
      toc_sticky: true
      read_time: false
      share: false
      comments: false
      sidebar:
        nav: "primary"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: single
      author_profile: false
      toc: true
      toc_label: "On this page"
      toc_icon: "list"
      toc_sticky: true
      read_time: false
      share: false
      comments: false

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pablomarcel"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/pablomarcel"

search: true
locale: "en-US"

sass:
  style: compressed
